# Disable the newline at the start of the prompt
add_newline = false

[aws]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[kubernetes]
disabled = false